[package]
name = "jakeland"
version = "0.1.0"
authors = ["Jake Stambaugh <jake.stambaugh@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rocket = { git = "https://github.com/SergioBenitez/Rocket.git" }