[development]
address = "localhost"
port = 8080
workers = 1
keep_alive = 5
log = "normal"
secret_key = "dev secret key dont tell"
limits = { forms = 32768 }

[staging]
address = "0.0.0.0"
port = 8080
workers = 1
keep_alive = 5
log = "normal"
secret_key = "This is not secure"
limits = { forms = 32768 }

[production]
address = "0.0.0.0"
port = 8080
workers = 12
keep_alive = 5
log = "critical"
secret_key = "TODO: generate better secret key"
limits = { forms = 32768 }